## ✨ feature(#이슈번호): 기능명
 

 
 ## 🔎 작업 내용
 
 - 어떤 기능이 추가되었는지, 어떤 문제가 해결되었는지 설명해주세요.
 
 - 기능이 어떤 방식으로 동작하는지도 간단히 정리해주세요.
 

 
 ## 🖼️ 작업 내용 미리보기
 
 <img src="파일주소" width="50%" height="50%"/>
 

 
 ## 💬 리뷰 요구사항
 
 > 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요  
 > ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
 
 ## ⏰ 예상 리뷰 시간
 
 5분
 
 ### ✔️ 이슈 닫기
 
 Closes #이슈번호 // 해당 이슈에 대한 작업이 완전히 끝난 경우
 Ref #이슈번호 // 해당 이슈에 대한 작업이 완전히 끝나지 않은 경우


**Reviewer의 의도가 명확하게 전달될 수 있도록, 아래와 같이 P-N 라벨을 리뷰 코멘트 앞에 추가해주세요.**
[예시] `P3) ~ 라인의 컨텍스트는 ~ 이유로 리뷰어 혹은 후속 작업자가 파악하기 힘들 것 같습니다. 주석이 추가되었으면 좋겠습니다.`

```
- P1: 꼭 반영해 주세요 (Request changes)
- P2: 적극적으로 고려해 주세요 (Request changes)
- P3: 웬만하면 반영해 주세요 (Comment)
- P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
- P5: 그냥 사소한 의견입니다 (Approve)
```